[package]
name = "form-data"
version = "0.2.3"
authors = ["Fangdun Cai <cfddream@gmail.com>"]
edition = "2018"
description = "AsyncRead/AsyncWrite/Stream `multipart/form-data`"
homepage = "https://github.com/viz-rs/form-data"
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["async", "form-data", "multipart", "http", "hyper"]
categories = ["asynchronous", "web-programming", "web-programming::http-server"]

include = [
  "Cargo.toml",
  "LICENSE-APACHE",
  "LICENSE-MIT",
  "README.md",
  "src/*.rs"
]

[dependencies]
anyhow = "1.0"
bytes = "1.0"
futures-util = { version = "0.3", default-features = false, features = ["io"] }
http = "0.2"
httparse = "1.3"
mime = "0.3"
memchr = "2.4"
tracing = "0.1"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
rand = "0.8"
async-fs = "1.5"
tempfile = "3.1"
hyper = { version = "0.14", features = ["stream", "server", "http1", "tcp"] }
tokio = { version = "1.0", default-features = false, features = ["macros", "rt-multi-thread"] }
tracing-subscriber = "0.2"
warp = "0.3"

[[example]]
name = "hyper"
path = "examples/hyper.rs"

[[example]]
name = "warp"
path = "examples/warp.rs"
