[package]
name = "form-data"
version = "0.0.5"
authors = ["Fangdun Cai <cfddream@gmail.com>"]
edition = "2018"
description = "AsyncRead/AsyncWrite/Stream `multipart/form-data`"
homepage = "https://github.com/viz-rs/form-data"
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["async", "form-data", "multipart", "http", "hyper"]
categories = ["asynchronous", "web-programming", "web-programming::http-server"]

[dependencies]
anyhow = "1.0"
bytes = "0.5"
futures-util = { version = "0.3", default-features = false, features = ["std", "io", "sink"] }
http = "0.2"
httparse = "1.3"
log = "0.4"
mime = "0.3"
mime-db = "0.1"
smol = "0.1"
thiserror = "1.0"
twoway = "0.2"

[dev-dependencies]
pretty_env_logger = "0.4"
hyper = { version = "0.13", default-features = false, features = ["stream"] }
futures-util = { version = "0.3", default-features = false, features = ["std", "io", "sink"] }
rand = "0.7"
tokio = { version = "0.2", default-features = false, features = ["macros"] }
tempfile = "3.1"

[[example]]
name = "hyper"
path = "examples/hyper.rs"
