[package]
name = "form-data"
version = "0.1.0-dev"
authors = ["Fangdun Cai <cfddream@gmail.com>"]
edition = "2018"
description = "AsyncRead/AsyncWrite/Stream `multipart/form-data`"
homepage = "https://github.com/viz-rs/form-data"
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["async", "form-data", "multipart", "http", "hyper"]
categories = ["asynchronous", "web-programming", "web-programming::http-server"]
publish = false

include = [
  "Cargo.toml",
  "LICENSE-APACHE",
  "LICENSE-MIT",
  "README.md",
  "src/*.rs"
]

[dependencies]
anyhow = "1.0"
bytes = "1.0"
futures-util = { version = "0.3", default-features = false, features = ["std", "io", "sink"] }
http = "0.2"
httparse = "1.3"
log = "0.4"
mime = "0.3"
mime-db = "1.1"
thiserror = "1.0"
twoway = "0.2"

[dev-dependencies]
smol = "1.2"
rand = "0.7"
async-fs = "1.5"
tempfile = "3.1"
pretty_env_logger = "0.4"
hyper = { version = "0.14", features = ["stream", "server", "http1", "tcp"] }
tokio = { version = "1.0", default-features = false, features = ["macros", "rt-multi-thread"] }

[[example]]
name = "hyper"
path = "examples/hyper.rs"
