on: [push]

name: CI

jobs:
  test:
    name: Test ${{ matrix.rust }}
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust (${{ matrix.rust }})
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true

      - uses: actions/checkout@v2

      - name: Async Feature 
        uses: actions-rs/cargo@v1
        env:
          RUST_LOG: trace
        with:
          command: test
          args: --test form-data --test hyper-body

      - name: Sync Feature 
        uses: actions-rs/cargo@v1
        env:
          RUST_LOG: trace
        with:
          command: test
          args: --test tiny-body --no-default-features --features="sync"
