on: [push]

name: CI

jobs:
  test:
    name: Test ${{ matrix.rust }}
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust (${{ matrix.rust }})
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - uses: actions/checkout@v2

      - uses: actions-rs/cargo@v1
        env: RUST_LOG=debug
        with:
          command: test
          args:
